image: ubuntu:latest

variables:
  PROJECT_DIR: "src/"

stages:
  - tests

default:
  tags:
    - docker
  before_script:
    - apt-get update
    - apt-get -y install check lcov clang-format valgrind cppcheck cmake pkg-config build-essential
    - cd ${PROJECT_DIR}

build_ok:
  stage: tests
  script:
    - make

tests:
  stage: tests
  script:
    - make lint
    - make test

leaks_check:
  stage: tests
  script:
    - make valgrind_tests
    - echo "status=${?}" >> leaks.log
  artifacts:
    paths:
      - leaks.log
    expire_in: "2 days"
