version: "3.3"

volumes:
  gitlab-runner-config:

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ="Europe/Moscow"
    restart: always

  test-instance:
    image: klyaxa/qt-dev:6.5.1
    volumes:
      - ./:/code/
    tty: true
    command: bash
