name: Lint and test

on:
  push:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    container: klyaxa/qt-dev:6.5.1
    defaults:
      run:
        working-directory: src
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: where-i-am
        run: |
          pwd
          ls -la

      - name: lint
        run: make lint

      - name: build is ok
        run: make build

      - name: test
        run: make test

      - name: check memory leaks
        run: make valgrind_tests
