name: Lint and test

on:
  push:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install dependencies
        run: >
          sudo apt-get install -y
          check lcov clang-format valgrind cppcheck mesa-utils libglfw3-dev

      - name: lint
        run: make lint

      - name: build is ok
        run: make

      - name: test
        run: make test

      - name: check memory leaks
        run: make valgrind_tests 

      - name: gcov coverage report
        run: make coverage_report

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
